language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: still-caverns-70902
  api_key:
    secure: ZgociFo8xpKQDoyfmEZrCniBt0zsfIs+mltRf3TiKRkN/bpL1Jd+sY3GBiecBaT5DqFfV0M3e0BnSV3KiSOYSfbSljfKoiytKxpP92UQYV49eiwuApRojveyzcqOVIkLQoHD29GI4pckh1Zxzr/AwfmaXoSRa/jSaTznVlVNqYWn1lZjynYLATE3POrvA14sK2c+RB7XtuisUWBb5K32mxTPiff77SX1ydMrkpvLUf/XfCF88T4hB5lFCZNrmnOtJENoBS3IdKm7xMjkFb9grxzypWTwLsapZ92z5OirXPIGZ1tv5xhIwgZC2cdU5Z4Eg48vrJwgfwBEIG3wZC7i9HXzabW8ZvrD2pUvtvoQx8Xn8EoG0GepSYs4cAMS/+Rk2bYm/jCItftUuwVXj3bs5fLz8CbZYAsdzU7iO78RI8la1lXzrm3KIZV0bMlJK/Al7be9k6zGfTGKmnUMDaInamIypqIiNraFMuvyL9ZZe3Tdd+Rb1sU9hgO00APxjU/Fsz+2GjubfwumbLF+eGhu/ZHDN0JsHSkqjlsFF6G+svMlXJeFYJJX+2hwtJxE0F65ty66EIpN23Wt+4r4P/CaB2BLp9HEcbp44T1rqF9O0zXU1tfDNRmwC1Wmz9dPXNHpgrMsu+mj7y+nRiZU84CmqK8W7VE4JIT/1d/9qgci17w=
